artifact_uri: file:///home/anantvaid/Documents/MadeWithML/model/0/860c0a61d2c14b1b82a118cbe86728f0/artifacts
end_time: 1635322999557
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 860c0a61d2c14b1b82a118cbe86728f0
run_uuid: 860c0a61d2c14b1b82a118cbe86728f0
source_name: ''
source_type: 4
source_version: ''
start_time: 1635322372982
status: 4
tags: []
user_id: anantvaid
