artifact_uri: file:///home/anantvaid/Documents/MadeWithML/model/0/6e37308f0cb14c609c86cf78cb8d45dd/artifacts
end_time: 1635322293131
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 6e37308f0cb14c609c86cf78cb8d45dd
run_uuid: 6e37308f0cb14c609c86cf78cb8d45dd
source_name: ''
source_type: 4
source_version: ''
start_time: 1635322293076
status: 4
tags: []
user_id: anantvaid
