artifact_uri: file:///home/anantvaid/Documents/MadeWithML/model/0/d010c5dd7f8c40adaa5dba58ebdfbd3a/artifacts
end_time: 1635322363694
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: d010c5dd7f8c40adaa5dba58ebdfbd3a
run_uuid: d010c5dd7f8c40adaa5dba58ebdfbd3a
source_name: ''
source_type: 4
source_version: ''
start_time: 1635322363633
status: 4
tags: []
user_id: anantvaid
